//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SreerastuMVC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SreerastuEntities1 : DbContext
    {
        public SreerastuEntities1()
            : base("name=SreerastuEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TBL_CustomerRegistration> TBL_CustomerRegistration { get; set; }
        public virtual DbSet<TBL_Employee> TBL_Employee { get; set; }
        public virtual DbSet<TBL_SubscriptionType> TBL_SubscriptionType { get; set; }
        public virtual DbSet<TBL_UserType> TBL_UserType { get; set; }
        public virtual DbSet<TBL_VendorCategory> TBL_VendorCategory { get; set; }
        public virtual DbSet<TBL_VendorRegistration> TBL_VendorRegistration { get; set; }
        public virtual DbSet<TBL_VendorStatus> TBL_VendorStatus { get; set; }
        public virtual DbSet<TBL_VendorType> TBL_VendorType { get; set; }
    }
}
