//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SreerastuMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_VendorRegistration
    {
        public int VendorID { get; set; }
        public string FName { get; set; }
        public string LName { get; set; }
        public string VendorUserName { get; set; }
        public string VendorPassword { get; set; }
        public string VendorBusinessName { get; set; }
        public Nullable<int> VendorCategoryID { get; set; }
        public Nullable<System.DateTime> BusinessStartedDate { get; set; }
        public Nullable<int> BusinessExperience { get; set; }
        public string ContactNumber { get; set; }
        public string AlternateContactNumber { get; set; }
        public string ContactPerson { get; set; }
        public string Email { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Location { get; set; }
        public Nullable<System.DateTime> BusinessRegistrationDate { get; set; }
        public Nullable<int> StatusID { get; set; }
        public Nullable<int> SubscriptionTypeID { get; set; }
        public Nullable<System.DateTime> SubscriptionExpiryDate { get; set; }
        public Nullable<System.DateTime> VendorRegistrationDate { get; set; }
        public string IDProof { get; set; }
        public string AddressProof { get; set; }
        public string SampleWorks { get; set; }
        public string BusinessLogo { get; set; }
        public Nullable<int> VerifiedBy { get; set; }
        public Nullable<int> ApprovedBy { get; set; }
        public Nullable<System.DateTime> VerifiedDate { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
    
        public virtual TBL_Employee TBL_Employee { get; set; }
        public virtual TBL_Employee TBL_Employee1 { get; set; }
        public virtual TBL_SubscriptionType TBL_SubscriptionType { get; set; }
        public virtual TBL_VendorCategory TBL_VendorCategory { get; set; }
        public virtual TBL_VendorStatus TBL_VendorStatus { get; set; }
    }
}
