//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SreerastuMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_Employee()
        {
            this.TBL_VendorRegistration = new HashSet<TBL_VendorRegistration>();
            this.TBL_VendorRegistration1 = new HashSet<TBL_VendorRegistration>();
        }
    
        public int EmpID { get; set; }
        public string EmpFName { get; set; }
        public string EmpLName { get; set; }
        public string EmpUserName { get; set; }
        public string EmpPassword { get; set; }
        public Nullable<System.DateTime> EmpDOB { get; set; }
        public string EmpContactNumber { get; set; }
        public string EmpEmail { get; set; }
        public string EmpRole { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_VendorRegistration> TBL_VendorRegistration { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_VendorRegistration> TBL_VendorRegistration1 { get; set; }
    }
}
